version: '3'

services:
  mysql_server:
    image: mysql:5.7
    ports:
      - "3310:3306"
    environment: 
      - MYSQL_DATABASE=challenge-database
      - MYSQL_USER=challenger
      - MYSQL_PASSWORD=cGFzc2NoYWxsZW5nZXI
      - MYSQL_ROOT_PASSWORD=cGFzc2NoYWxsZW5nZXI

  app:
    build: .
    command: yarn start
    ports:
      - "3800:3800"
    volumes:
      - .:/usr/app
